version: '3.8'

networks:
  microservices-network:
    driver: bridge
  keycloak-network:
    driver: bridge

services:

  customer-service:
    image: customer-service:latest
    container_name: customer-service
    env_file:
      - ../secrets/customer-service.env
    restart: always
    networks:
      - microservices-network

  product-service:
    image: product-service:latest
    container_name: product-service
    networks:
      - microservices-network
    env_file:
      - ../secrets/product-service.env
    restart: always

  inquiry-service:
    image: inquiry-service:latest
    container_name: inquiry-service
    networks:
      - microservices-network
    env_file:
      - ../secrets/inquiry-service.env
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    networks:
      - keycloak-network
    ports:
      - 8484:8080
    depends_on:
      - postgres-keycloak-db
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "admin"
    links:
      - "postgres-keycloak-db:postgres-keycloak-db"

  gateway:
    image: nginx:latest
    container_name: gateway
    restart: unless-stopped
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/log:/var/log/nginx
      - ../secrets/iprody_server.crt:/etc/nginx/ssl/iprody.crt
      - ../secrets/iprody_server.key:/etc/nginx/ssl/iprody.key
    ports:
      - 443:443
    depends_on:
      - customer-service
      - product-service
      - inquiry-service
    networks:
      - microservices-network
